### ISSUE TITLE
incorrect secret code

### ISSUE THREAD

**Issue by rabdallah1512** [abbas-gheydi/radotp#13]
Hi,
After installation and I can access the web interface without problem with admi/admin, I encountered a problem that the forewall fortigate can not reach the radotp server, although I receive logs on radotp that connection accept from the user who I have the fortigate test, it displays the error message on the fortigate side: incorrect secret code, although it is correct, I also test it locally and works. Thank you for your help.

**Comment by abbas-gheydi** [comment]
Dear @rabdallah1512 , I believe your problem is similar to the issue described in #11

**Comment by abbas-gheydi** [comment]
there is no limitation on the number of users you can add to RadOTP. It is unlimited.

**Comment by rabdallah1512** [comment]
Thank you for the solution, yes indeed, the solution is indeed functional, it's just that the web interface I can add users and generate a QR code with the interface, but after that I cannot find these users no I can recover given them, just when I consult the database, thank you

**Comment by abbas-gheydi** [comment]
If a user forgets their QR code, the solution is to regenerate it for them. :)

If I understand your issue correctly, you're looking to create users in bulk, and the web interface isn't suitable for bulk actions. That’s correct. To solve this, you can enable the REST API and make sure you set the token for the REST API in radotp.conf. This way, you can write a script to create as many users as you need, with minimal effort. The API documentation is also available in the RadOTP web interface in Swagger format.

Additionally, I’ve just closed the issue "incorrect secret code" because it has been resolved.
